import{a as L,S as w,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const E="48273620-0132f44a126025621a132d295",S="https://pixabay.com/api/",q=async(t,o,n)=>{const s=new URLSearchParams({key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n,page:o});return(await L.get(`${S}?${s}`)).data},R=(t,o)=>{const n=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:h,comments:m,downloads:y})=>`
      <li class="gallery-card">
        <a href="${e}">
          <img src="${s}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p><strong>Likes:</strong> ${i}</p>
          <p><strong>Views:</strong> ${h}</p>
          <p><strong>Comments:</strong> ${m}</p>
          <p><strong>Downloads:</strong> ${y}</p>
        </div>
      </li>`).join("");o.insertAdjacentHTML("beforeend",n)},b=document.querySelector(".js-search-form"),u=document.querySelector(".js-gallery"),f=document.querySelector(".loader"),c=document.querySelector(".js-load-more");c.hidden=!0;const v=new w(".js-gallery a");let d="",a=1;const g=15,P=()=>f.hidden=!1,$=()=>f.hidden=!0,p=async()=>{try{P();const t=await q(d,a,g);if(t.hits.length===0&&a===1){l.warning({title:"No Results",message:"No images found. Try a different query.",position:"topRight",timeout:3e3});return}R(t.hits,u),v.refresh(),a*g>=t.totalHits?(c.hidden=!0,l.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight",timeout:3e3})):c.hidden=!1}catch(t){l.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight",timeout:3e3}),console.error(t)}finally{$()}},j=async t=>{if(t.preventDefault(),u.innerHTML="",d=t.target.elements.user_query.value.trim(),a=1,c.hidden=!0,!d){l.error({title:"Error",message:"Please enter a search query!",position:"topRight",timeout:3e3});return}await p()},O=async()=>{a+=1,await p();const{height:t}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})};b.addEventListener("submit",j);c.addEventListener("click",O);
//# sourceMappingURL=index.js.map
